sudo: required
os: osx
branches:
  only:
    - master
before_install:
- sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-full
script:
- pdflatex pdflatex --enable-write18 -shell-escape -synctex=1 -interaction=nonstopmode -halt-on-error *.tex