sudo: required
os: osx
branches:
  only:
    - master
before_install:
- /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
- brew tap caskroom/cask
- brew cask install mactex